spring.application.name=jnpay
spring.datasource.url=jdbc:postgresql://localhost:5432/o_pgbanco_jnpay
spring.datasource.username=app_web
spring.datasource.password=123456
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl